export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IklzYWMiLCJlbWFpbCI6ImlzYWNAdGVzdGUuY29tIiwiaWF0IjoxNzE4NjQyMTMyLCJleHAiOjE3MTkwNzQxMzIsImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiIxIn0.3j_lM3WFKBjVjFGTOWsitaxgaufB3TUcpcsQfMVqk:c';
